### ISSUE TITLE
Tools directory in production package versions

### ISSUE THREAD

**Issue by strorch** [sebastianbergmann/diff#106]
### Hello!

My phpstorm is out of memory every time when I'm trying to navigate class from symfony package, for example **Symfony\Component\Console\Command\Command**.
It happens because this class also contains in files from tools dir(*php-cs-fixer, composer* each of it has more than 2mb size and its really hard to open with IDE).
This files can't be fully ignored by Storm or maybe I just can't find how to do it.
Can you please give me an advice what should I do with it?

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to report. This repository has a `tools` directory, but you only get that if you check out this repository. If you install a release of the library that is developed in this repository then you do not get the `tools` directory because it is ignored in `.gitattributes`.
