### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/diff#65]

**Comment by weirdan** [comment]
Has the release actually happened? It's not on packagist, and this prohibits updating to latest version of sebastian/comparator (which strictly requires diff v2+).

**Comment by SpacePossum** [comment]
It has been rolled back because of compat issues with some released versions of PHPUnit.
I have no view on the expected releases of updated package(s) so I can't provide more useful information.
However I think the compat issues has been resolved within the `diff` package so a re-release of 2.0 could be soon.

**Comment by weirdan** [comment]
No worries, I can leave with that 'dependencies are outdated' message for some time. Thanks for explaining the situation though, I thought I might be going crazy when I saw successful builds on travis that used v2 package, but couldn't find it on packagist.
