### ISSUE TITLE
List SpacePossum as maintainer

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/diff#78]
@SpacePossum I would like to list you as maintainer in `composer.json`. For that I need your realname and email.

**Comment by SpacePossum** [comment]
Hi @sebastianbergmann and thanks for this consideration!

I hope you don't mind if prefer to pass, as I feel that I'm not one of the persons that did the real heavy work on the package and I feel more comfortable in the background. Besides I'm leaving PHP / OSS because I can no longer combine with other things. Leaving my email here could be taken by people that they could contact me about it, but than I would've to disappoint them because I left. But thanks again! :)

**Comment by sebastianbergmann** [comment]
Sorry to hear that. Thank you for all the work you did!
